name: Cache Node and NPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on pnpm-lock.yaml"

inputs:
  node-version:
    description: "Node version to use"
    required: true
    default: 20.x
  working-dir:
    description: "Working directory of the application"
    default: "."
  target-env:
    description: "dev or prod. Controls whether dev deps are installed"
    default: dev

runs:
  using: "composite"
  steps:
    - name: Setup pnpm v9
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup NodeJS Version ${{inputs.node-version}}
      uses: actions/setup-node@v4
      with:
        version: ${{inputs.node-version}}

    - name: Cache dependencies
      id: cache-deps-id
      uses: actions/cache@v3
      with:
        path: ${{inputs.working-dir}}/node_modules
        key: deps-node-modules-${{hashFiles(format('{0}/{1}', inputs.working-dir, 'pnpm-lock.yaml'))}}

    - name: Install dependencies
      if: steps.cache-deps-id.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{inputs.working-dir}}
      run: |
        echo ${{inputs.target-env}}
        ${{inputs.target-env == 'dev' && 'pnpm install' || 'pnpm install --prod'}}
