name: 05 - 2 - Event Filters and Activity Types
on: workflow_dispatch

# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echoing close
        run: echo "Runs whenever PR is closed"
