name: 06 - Contexts
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
  RUN_NAME: 06 - Contexts | DEBUG - ${{inputs.debug}}
  MY_WORKFLOW_VAR: "workflow"
  MY_OVERRITEN_VAR: "workflow"

jobs:
  echo-data:
    env:
      MY_JOB_VAR: "job"
      MY_OVERRITEN_VAR: "job"
    runs-on: ubuntu-latest
    steps:
      - name: Display information
        run: |
          echo "Event name: ${{github.event_name}}"
          echo "Ref: ${{github.ref}}"
          echo "SHA: ${{github.sha}}"
          echo "Actor: ${{github.actor}}"
          echo "Workflow: ${{github.workflow}}"
          echo "Run ID: ${{github.run_id}}"
          echo "Run number: ${{github.run_number}}"

      - name: Retrieve variable
        run: echo "Variable is ${{vars.MY_VAR}}"

      - name: Print Env Variables
        env:
          MY_OVERRITEN_VAR: "step"
        run: |
          echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}"
          echo "Overriten env: ${{env.MY_OVERRITEN_VAR}}"
