name: 07 - Using Expressions
run-name: Using Expressions | DEBUG - ${{inputs.debug && 'ON' || 'OFF'}}
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: "[Debug] - Print start-up data"
        if: ${{inputs.debug == true}}
        run: |
          echo "Debug value is: ${{inputs.debug}}"
          echo "Triggered by: ${{github.event_name}}"
          echo "Branch: ${{github.ref_name}}"
          echo "Commit SHA ${{github.sha}}"
          echo "Runner OS: ${{runner.os}}"

      - name: "[Debug] - Print when triggered from main"
        if: ${{inputs.debug == true && github.ref_name == 'main' }}
        run: |
          echo "I was triggered from main"

      - name: Always greeting
        run: echo "Hello world"
