name: 09 - Using Functions
on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: exit 1

      - name: I will be skipped
        if: ${{success()}}
        run: echo "I printed because previous step succeeded"

      - name: I will execute
        if: ${{failure()}}
        run: echo "One of prev jobs failed"

      - name: I also will execute
        if: ${{!cancelled()}}
        run: echo 'I print if not cancelled'

      - name: I will execute when cancelled
        if: ${{cancelled()}}
        run: echo "Smth Cancelled"
