name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status-input:
        type: choice
        default: success
        options:
          - success
          - failure

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-output: ${{steps.build.outputs.STATUS}}
      output1: output1
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_OUTPUT

      - name: Build
        id: build
        run: |
          echo "STATUS=${{inputs.build-status-input}}" >> "$GITHUB_OUTPUT"
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT
          echo "mistake=trur" > "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{needs.build.outputs.build-output == 'success'}}
    steps:
      - name: Deploy
        run: echo "Deploying"
      - name: Print Outputs
        run: echo "Output1 value is ${{needs.build.outputs.output1}}"
