name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Execute cache step?
        type: boolean
        default: true
      node-version:
        type: choice
        options:
          - 18.x
          - 19.x
          - 20.x

jobs:
  build:
    needs: install-deps
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}

      - name: Download cached pnpm dependencies
        id: cache-pnpm
        uses: actions/cache@v3
        with:
          path: react-app/node_modules
          key: ${{needs.install-deps.outputs.deps-cache-key}}

      - name: Building
        run: pnpm build

      - name: Deploy to nonprod
        run: echo "Deploing to non prod"

  install-deps:
    runs-on: ubuntu-latest
    outputs:
      deps-cache-key: ${{steps.cache-key.outputs.CACHE_KEY}}
    defaults:
      run:
        working-directory: react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          version: ${{inputs.node-version}}

      - name: Calculate cache key
        id: cache-key
        run: echo "CACHE_KEY=deps-node-modules-${{hashFiles('react-app/pnpm-lock.yaml')}}" >> "$GITHUB_OUTPUT"

      - name: Download cached deps
        uses: actions/cache@v3
        with:
          path: react-app/node_modules
          key: ${{steps.cache-key.outputs.CACHE_KEY}}
  linting:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          version: ${{inputs.node-version}}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: "[linting] Download cached dep"
        uses: actions/cache@v3
        with:
          path: react-app/node_modules
          key: ${{needs.install-deps.outputs.deps-cache-key}}

      - name: Building
        run: pnpm build

      - name: Linting
        run: echo "Linting..."
