name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Execute cache step?
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: pnpm install
      - name: Building
        run: pnpm build
      - name: Deploy to nonprod
        run: echo "Deploing to non prod"
