name: 15 - Working with Matrices
on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]
        os: [ubuntu-latest, windows-latest]
    name: ${{matrix.os}}-${{matrix.node-version}}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Print OS and Node versions
        run: echo "Running on ${{matrix.os}} and node is ${{matrix.node-version}}"
