name: 15 - Working with Matrices
on:
  workflow_dispatch:
    inputs:
      fail-fast:
        type: boolean
        default: false

jobs:
  backwards-compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{inputs.fail-fast}}
      matrix:
        node-version: [19.x]
        os: [windows-latest]
        include:
          - os: ubuntu-latest
            node-version: 16.x

          - os: ubuntu-latest
            tag: experimental
            node-version: 21.x

    name: ${{matrix.os}}-${{matrix.node-version}}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Fail if experimental
        if: ${{matrix.tag == 'experimental'}}
        run: exit 1

      - name: Upload test results
        run: echo "${{inputs.fail-fast}}"
  include-example:
    runs-on: ubuntu-latest
    name: ${{matrix.color}} - ${{matrix.shape}} - ${{matrix.size}}
    strategy:
      matrix:
        color:
          - red
          - green
        shape:
          - circle
          - square
        size:
          - small
          - large
        include:
          - opacity: 50
          - color: red
            opacity: 75
          - shape: circle
            opacity: 100
          - color: red
            shape: triangle
        exclude:
          - opacity: 75
    steps:
      - name: Dummy step
        run: echo ${{matrix.color}} - ${{matrix.shape}} - ${{matrix.size}} - ${{matrix.opacity}}
