name: 15 - Working with Matrices
on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
        os: [windows-latest]
        include:
          - os: ubuntu-latest
            node-version: 16.x

          - os: ubuntu-latest
            tag: experimental

    name: ${{matrix.os}}-${{matrix.node-version}}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Print OS and Node versions
        run: echo "Running on ${{matrix.os}} and node is ${{matrix.node-version}}"
