name: 16 - Working with Environments
run-name: "Working with env - ${{inputs.target-env}}"

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging

jobs:
  echo:
    runs-on: ubuntu-latest
    environment:
      name: prod
    env:
      my-env-value: ${{vars.environment || 'default value'}}
    steps:
      - name: Echo vars
        run: echo "Env variable - $my-env-value "
