name: 16 - Working with Environments
run-name: "Working with env - ${{inputs.target-env}}"

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
    env:
      my-env-value: ${{vars.MY_ENV_VALUE}}
    steps:
      - name: Echo vars
        run: echo "Deploy staging - ${{env.my-env-value}}"
  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: E2E tests
        run: echo "Running e2e tests"
  deploy-prod:
    runs-on: ubuntu-latest
    needs: e2e-tests
    environment:
      name: prod
    env:
      my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
    steps:
      - name: Echo vars
        run: echo "Deploying to prod"
