name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env = ${{inputs.target-env}}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        options:
          - dev
          - prod

env:
  WORKING_DIRECTORY: react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKING_DIRECTORY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and NPM Deps
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 20.x
          working-dir: ${{env.WORKING_DIRECTORY}}
          target-env: ${{inputs.target-env}}
      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
