name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS

on:
  workflow_dispatch:

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Node and NPM Deps
      #   uses: ./.github/actions/composite-cache-deps
      #   with:
      #     node-version: 20.x
      #     working-dir: ${{env.WORKING_DIRECTORY}}
      #     target-env: ${{inputs.target-env}}

      - name: Check for dependency updates
        uses: ././github/actions/js-dependency-update
